[package]
name = "winzsh-theme"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "WinZSH theme engine contracts"

[dependencies]
winzsh-core = { workspace = true }
winzsh-error = { workspace = true }
winzsh-fs = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
