[package]
name = "winzsh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "WinZSH CLI binary"
readme = "../../README.md"

[[bin]]
name = "winzsh"
path = "src/main.rs"

[dependencies]
winzsh-cli = { workspace = true }
winzsh-log = { workspace = true }

[lints]
workspace = true
